"""I/O helpers: GeoTIFF reading and shapefile export.

The one hard rule in this module: a shapefile's .prj must come from the
CRS of the **source raster**, never from a browser view. Web Mercator is
explicitly rejected as an export target - it would silently degrade
polar glacier geometry to metres that mean nothing on the ground.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np
import rasterio
from pyproj import CRS
from shapely.geometry import Polygon


class IOError(RuntimeError):
    """Raised on raster/shapefile I/O problems.

    Name intentionally shadows the builtin: in this module, "IO error" is
    the only meaningful failure mode, and callers catch this specific type.
    """


@dataclass(frozen=True)
class Raster:
    """A GeoTIFF loaded in memory.

    Attributes
    ----------
    data:
        Pixel array with shape ``(bands, height, width)``.
    transform:
        Affine transform mapping pixel coordinates to CRS coordinates.
    crs:
        The raster's CRS (pyproj object).
    path:
        Absolute path the raster was read from (for diagnostics).
    """

    data: np.ndarray
    transform: rasterio.Affine
    crs: CRS
    path: Path

    @property
    def shape(self) -> tuple[int, int]:
        return self.data.shape[1], self.data.shape[2]


def load_geotiff(path: str | Path) -> Raster:
    """Read a GeoTIFF into a :class:`Raster`.

    Loads all bands. Raises :class:`IOError` if the file has no CRS
    (that would break shapefile export later).
    """
    p = Path(path).expanduser().resolve()
    if not p.exists():
        raise IOError(f"GeoTIFF not found: {p}")
    with rasterio.open(p) as src:
        if src.crs is None:
            raise IOError(
                f"GeoTIFF has no CRS: {p}. "
                "Cannot export a shapefile without a defined CRS."
            )
        data = src.read()
        transform = src.transform
        crs = CRS.from_wkt(src.crs.to_wkt())
    return Raster(data=data, transform=transform, crs=crs, path=p)


def export_shapefile(
    polygons: list[Polygon],
    names: list[str] | None = None,
    crs: CRS | None = None,
    out_dir: str | Path = ".",
    name: str = "glacier",
) -> list[Path]:
    """Write one row per polygon to a shapefile in ``out_dir``.

    Parameters
    ----------
    polygons:
        One Polygon per glacier. Every item becomes a separate row in the
        attribute table (a single MultiPolygon would not - that is exactly
        why this function accepts a list).
    names:
        Optional names, one per polygon. Missing entries fall back to
        ``glacier_<i>``. Stored in the ``name`` field of the .dbf.
    crs:
        CRS of every polygon (same for all). Must NOT be EPSG:4326 - the
        caller is expected to reproject first if the map is in lat/lon.
    out_dir:
        Directory to write into; created if missing.
    name:
        Base filename without extension.

    Returns the list of written sidecar files (``.shp``, ``.shx``,
    ``.dbf``, ``.prj``, ``.cpg``). The caller can zip them.

    The ``.prj`` is generated by GDAL from ``crs``. The caller MUST pass
    the raster's CRS (see :func:`load_geotiff`), not a display CRS.
    """
    if not polygons:
        raise IOError("Refusing to export an empty polygon collection.")
    if crs is None:
        raise IOError("CRS is required to export a shapefile.")
    for i, poly in enumerate(polygons):
        if poly.is_empty:
            raise IOError(f"Polygon at index {i} is empty.")
        if not poly.is_valid:
            raise IOError(f"Polygon at index {i} is invalid.")
    if crs.is_geographic and crs.to_epsg() == 4326:
        raise IOError(
            "Refusing to export in EPSG:4326 as-is; reproject to a metric "
            "CRS (UTM / Polar Stereographic) before export."
        )

    # Import lazily so the rest of the package imports without geopandas.
    import geopandas as gpd

    out = Path(out_dir).expanduser().resolve()
    out.mkdir(parents=True, exist_ok=True)

    resolved_names = []
    for i in range(len(polygons)):
        if names is not None and i < len(names) and names[i]:
            resolved_names.append(str(names[i]))
        else:
            resolved_names.append(f"glacier_{i + 1}")

    # Attribute table columns. Shapefile field names are limited to 10
    # characters - "name" and "fid" are safe; longer names get truncated
    # by GDAL with a warning.
    gdf = gpd.GeoDataFrame(
        {
            "fid": list(range(len(polygons))),
            "name": resolved_names,
            "geometry": polygons,
        },
        crs=crs.to_wkt(),
    )
    shp_path = out / f"{name}.shp"
    gdf.to_file(shp_path, driver="ESRI Shapefile", encoding="utf-8")

    written = sorted(out.glob(f"{name}.*"))
    if not written:
        raise IOError(f"Shapefile writer reported success but no files at {out}")
    # Sanity: .prj must exist and be non-empty, otherwise the shapefile is
    # unanchored and ArcGIS/QGIS will refuse to place it on a map.
    prj = out / f"{name}.prj"
    if not prj.exists() or prj.stat().st_size == 0:
        raise IOError(
            "Shapefile written without a .prj - CRS was not propagated. "
            "This is a bug; refusing to return a partially usable result."
        )
    return written


def render_tile_png(
    raster_path: Path,
    z: int,
    x: int,
    y: int,
    tile_size: int = 256,
) -> bytes:
    """Render one tile of the *source* raster as an RGBA PNG.

    The tile grid is defined in the raster's own CRS (not Web Mercator):

      * ``z = 0`` — the whole raster fits into a single ``tile_size`` square.
      * ``z = N`` — the raster is split into ``2**N`` by ``2**N`` tiles.

    ``(x, y)`` are tile column/row within that grid, with ``(0, 0)`` at the
    **top-left** corner of the raster (rasterio's row 0, col 0). Tiles that
    fall completely outside the raster return a transparent PNG; partial
    tiles are padded with transparency.

    Why this shape and not standard XYZ/Web Mercator: the raster may be in
    UTM, Polar Stereographic, or any other CRS. Reprojecting on the fly for
    every tile would be slow and lossy, so we cut tiles in the raster CRS
    and let OpenLayers' TileGrid use the same CRS.
    """
    import rasterio
    from rasterio.windows import Window
    from PIL import Image

    # Guard: negative zoom is not part of the protocol, and 2**z must fit
    # in an int without blowing memory. 25 is a very generous ceiling for
    # a local tool (a 2^25 grid is astronomically more than any raster we
    # would ever open).
    if z < 0 or z > 25:
        raise ValueError(f"zoom out of range: {z}")

    with rasterio.open(raster_path) as src:
        raster_w = src.width
        raster_h = src.height
        bands = src.count

        # Number of tiles along the *longer* axis at this zoom. Using the
        # longer axis keeps tiles square in pixel space even for very
        # elongated rasters.
        grid = 2 ** z
        span_px = max(raster_w, raster_h) / grid  # source pixels per tile

        # Window bounds in source pixels for this tile. Note: (0,0) is the
        # top-left corner, so row_off increases downwards, consistent with
        # rasterio's row direction and OpenLayers' tile origin for rasters
        # whose Y axis points up (the tile grid stores origin as top-left
        # and works in raster pixel space).
        col_off = int(round(x * span_px))
        row_off = int(round(y * span_px))
        win_w = max(1, int(round(span_px)))
        win_h = win_w

        # Fully outside the raster → transparent tile.
        if col_off >= raster_w or row_off >= raster_h or col_off + win_w <= 0 or row_off + win_h <= 0:
            return _transparent_png(tile_size)

        # Clamp the window to the raster. After clamping we track how much
        # padding is needed so the source pixels line up with the correct
        # corner of the output tile.
        src_col = max(0, col_off)
        src_row = max(0, row_off)
        src_col_end = min(raster_w, col_off + win_w)
        src_row_end = min(raster_h, row_off + win_h)
        read_w = max(1, src_col_end - src_col)
        read_h = max(1, src_row_end - src_row)

        window = Window(col_offset=src_col, row_offset=src_row, width=read_w, height=read_h)
        data = src.read(window=window)  # shape (bands, read_h, read_w)

    # --- Normalize each band to 0..255 and build an RGBA image -------------
    # We keep the original (min-max) stretch to match the preview look.
    def _stretch(band):
        band = band.astype(np.float32)
        lo = float(np.nanmin(band))
        hi = float(np.nanmax(band))
        if hi <= lo:
            return np.zeros_like(band, dtype=np.uint8)
        return ((band - lo) / (hi - lo) * 255.0).clip(0, 255).astype(np.uint8)

    if bands >= 3:
        rgb = np.stack([_stretch(data[i]) for i in range(3)], axis=-1)
        img = Image.fromarray(rgb, mode="RGB")
    else:
        gray = _stretch(data[0])
        img = Image.fromarray(gray, mode="L").convert("RGB")

    # Resample the read window to exactly tile_size x tile_size.
    if (read_w, read_h) != (tile_size, tile_size):
        img = img.resize((tile_size, tile_size), Image.BILINEAR)

    # Place the resized content into the correct corner of a transparent
    # tile_size x tile_size canvas, so partial edge tiles do not smear.
    canvas = Image.new("RGBA", (tile_size, tile_size), (0, 0, 0, 0))
    paste_x = int(round((src_col - col_off) * tile_size / win_w))
    paste_y = int(round((src_row - row_off) * tile_size / win_h))
    content_w = int(round((src_col_end - src_col) * tile_size / win_w))
    content_h = int(round((src_row_end - src_row) * tile_size / win_h))
    # Final guard: if the tile touches the raster only by a sub-pixel sliver,
    # content_w/content_h can come out as 0. Paste a single transparent pixel
    # and skip — the tile is effectively empty.
    if content_w > 0 and content_h > 0:
        cropped = img.resize((content_w, content_h), Image.BILINEAR)
        canvas.paste(cropped, (paste_x, paste_y))

    buf = stdlib_io.BytesIO()
    canvas.save(buf, format="PNG", optimize=True)
    return buf.getvalue()


def _transparent_png(tile_size: int = 256) -> bytes:
    """A fully transparent tile of the given side length."""
    from PIL import Image

    buf = stdlib_io.BytesIO()
    Image.new("RGBA", (tile_size, tile_size), (0, 0, 0, 0)).save(buf, format="PNG")
    return buf.getvalue()


def polygon_to_crs(polygon: Polygon, from_crs: CRS, to_crs: CRS) -> Polygon:
    """Reproject a shapely polygon between two CRSs.

    Used when the UI works in a display CRS (e.g. Web Mercator for OSM
    tiles) but the export must be in the raster CRS.
    """
    from pyproj import Transformer
    from shapely.ops import transform as shapely_transform

    transformer = Transformer.from_crs(from_crs, to_crs, always_xy=True)
    return shapely_transform(transformer.transform, polygon)
