"""I/O helpers: GeoTIFF reading and shapefile export.

The one hard rule in this module: a shapefile's .prj must come from the
CRS of the **source raster**, never from a browser view. Web Mercator is
explicitly rejected as an export target - it would silently degrade
polar glacier geometry to metres that mean nothing on the ground.
"""

from __future__ import annotations

import io as stdlib_io
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import rasterio
from pyproj import CRS
from shapely.geometry import Polygon


class IOError(RuntimeError):
    """Raised on raster/shapefile I/O problems.

    Name intentionally shadows the builtin: in this module, "IO error" is
    the only meaningful failure mode, and callers catch this specific type.
    """


@dataclass(frozen=True)
class Raster:
    """A GeoTIFF loaded in memory.

    Attributes
    ----------
    data:
        Pixel array with shape ``(bands, height, width)``.
    transform:
        Affine transform mapping pixel coordinates to CRS coordinates.
    crs:
        The raster's CRS (pyproj object).
    path:
        Absolute path the raster was read from (for diagnostics).
    """

    data: np.ndarray
    transform: rasterio.Affine
    crs: CRS
    path: Path

    @property
    def shape(self) -> tuple[int, int]:
        return self.data.shape[1], self.data.shape[2]


def load_geotiff(path: str | Path) -> Raster:
    """Read a GeoTIFF into a :class:`Raster`.

    Loads all bands. Raises :class:`IOError` if the file has no CRS
    (that would break shapefile export later).
    """
    p = Path(path).expanduser().resolve()
    if not p.exists():
        raise IOError(f"GeoTIFF not found: {p}")
    with rasterio.open(p) as src:
        if src.crs is None:
            raise IOError(
                f"GeoTIFF has no CRS: {p}. "
                "Cannot export a shapefile without a defined CRS."
            )
        data = src.read()
        transform = src.transform
        crs = CRS.from_wkt(src.crs.to_wkt())
    return Raster(data=data, transform=transform, crs=crs, path=p)


def export_shapefile(
    polygons: list[Polygon],
    names: list[str] | None = None,
    crs: CRS | None = None,
    out_dir: str | Path = ".",
    name: str = "glacier",
) -> list[Path]:
    """Write one row per polygon to a shapefile in ``out_dir``.

    Parameters
    ----------
    polygons:
        One Polygon per glacier. Every item becomes a separate row in the
        attribute table (a single MultiPolygon would not - that is exactly
        why this function accepts a list).
    names:
        Optional names, one per polygon. Missing entries fall back to
        ``glacier_<i>``. Stored in the ``name`` field of the .dbf.
    crs:
        CRS of every polygon (same for all). Must NOT be EPSG:4326 - the
        caller is expected to reproject first if the map is in lat/lon.
    out_dir:
        Directory to write into; created if missing.
    name:
        Base filename without extension.

    Returns the list of written sidecar files (``.shp``, ``.shx``,
    ``.dbf``, ``.prj``, ``.cpg``). The caller can zip them.

    The ``.prj`` is generated by GDAL from ``crs``. The caller MUST pass
    the raster's CRS (see :func:`load_geotiff`), not a display CRS.
    """
    if not polygons:
        raise IOError("Refusing to export an empty polygon collection.")
    if crs is None:
        raise IOError("CRS is required to export a shapefile.")
    for i, poly in enumerate(polygons):
        if poly.is_empty:
            raise IOError(f"Polygon at index {i} is empty.")
        if not poly.is_valid:
            raise IOError(f"Polygon at index {i} is invalid.")
    if crs.is_geographic and crs.to_epsg() == 4326:
        raise IOError(
            "Refusing to export in EPSG:4326 as-is; reproject to a metric "
            "CRS (UTM / Polar Stereographic) before export."
        )

    # Import lazily so the rest of the package imports without geopandas.
    import geopandas as gpd

    out = Path(out_dir).expanduser().resolve()
    out.mkdir(parents=True, exist_ok=True)

    resolved_names = []
    for i in range(len(polygons)):
        if names is not None and i < len(names) and names[i]:
            resolved_names.append(str(names[i]))
        else:
            resolved_names.append(f"glacier_{i + 1}")

    # Attribute table columns. Shapefile field names are limited to 10
    # characters - "name" and "fid" are safe; longer names get truncated
    # by GDAL with a warning.
    gdf = gpd.GeoDataFrame(
        {
            "fid": list(range(len(polygons))),
            "name": resolved_names,
            "geometry": polygons,
        },
        crs=crs.to_wkt(),
    )
    shp_path = out / f"{name}.shp"
    gdf.to_file(shp_path, driver="ESRI Shapefile", encoding="utf-8")

    written = sorted(out.glob(f"{name}.*"))
    if not written:
        raise IOError(f"Shapefile writer reported success but no files at {out}")
    # Sanity: .prj must exist and be non-empty, otherwise the shapefile is
    # unanchored and ArcGIS/QGIS will refuse to place it on a map.
    prj = out / f"{name}.prj"
    if not prj.exists() or prj.stat().st_size == 0:
        raise IOError(
            "Shapefile written without a .prj - CRS was not propagated. "
            "This is a bug; refusing to return a partially usable result."
        )
    return written


def render_tile_png(
    raster_path: Path,
    z: int,
    x: int,
    y: int,
    tile_size: int = 256,
) -> bytes:
    """Render one tile of the *source* raster as an RGBA PNG.

    The tile grid is defined in the raster's own CRS (not Web Mercator):

      * ``z = 0`` — the whole raster fits into a single ``tile_size`` square.
      * ``z = N`` — the raster is split into ``2**N`` by ``2**N`` tiles.

    ``(x, y)`` are tile column/row within that grid, with ``(0, 0)`` at the
    **top-left** corner of the raster (rasterio's row 0, col 0). Tiles that
    fall completely outside the raster return a transparent PNG; partial
    tiles are padded with transparency.

    Why this shape and not standard XYZ/Web Mercator: the raster may be in
    UTM, Polar Stereographic, or any other CRS. Reprojecting on the fly for
    every tile would be slow and lossy, so we cut tiles in the raster CRS
    and let OpenLayers' TileGrid use the same CRS.
    """
    import rasterio
    from rasterio.windows import Window
    from PIL import Image

    # Guard: negative zoom is not part of the protocol, and 2**z must fit
    # in an int without blowing memory. 25 is a very generous ceiling for
    # a local tool (a 2^25 grid is astronomically more than any raster we
    # would ever open).
    if z < 0 or z > 25:
        raise ValueError(f"zoom out of range: {z}")

    with rasterio.open(raster_path) as src:
        raster_w = src.width
        raster_h = src.height
        bands = src.count
        transform = src.transform
        # Full raster extent in CRS units (left, bottom, right, top).
        left, top = transform * (0, 0)
        right, bottom = transform * (raster_w, raster_h)
        width_crs = right - left
        height_crs = top - bottom
        # The tile grid is SQUARE in CRS, matching the frontend TileGrid:
        # maxSpan CRS units cover 2**z tiles on each axis, so one tile
        # spans maxSpan / 2**z CRS units in BOTH directions. Origin is the
        # raster's top-left corner (left, top). This is the crucial part —
        # using pixel-based span_px (previous version) made the grid square
        # in *pixels*, not in CRS, so a non-square raster produced partial
        # tiles and visible seams.
        max_span_crs = max(width_crs, height_crs)
        grid = 2 ** z
        tile_span_crs = max_span_crs / grid

        # DEBUG: log the raster geometry + computed tile span.
        import sys as _sys
        _sys.stderr.write(
            f"[render_tile_png] z={z} x={x} y={y}\n"
            f"  raster_w={raster_w} raster_h={raster_h} bands={bands}\n"
            f"  left={left:.2f} top={top:.2f} right={right:.2f} bottom={bottom:.2f}\n"
            f"  width_crs={width_crs:.2f} height_crs={height_crs:.2f} max_span_crs={max_span_crs:.2f}\n"
            f"  grid={grid} tile_span_crs={tile_span_crs:.4f}\n"
        )
        _sys.stderr.flush()

        # CRS bounds of this tile (x grows right, y grows down from top).
        tile_left = left + x * tile_span_crs
        tile_right = tile_left + tile_span_crs
        tile_top = top - y * tile_span_crs
        tile_bottom = tile_top - tile_span_crs

        _sys.stderr.write(
            f"  tile_left={tile_left:.2f} tile_right={tile_right:.2f} "
            f"tile_top={tile_top:.2f} tile_bottom={tile_bottom:.2f}\n"
        )
        _sys.stderr.flush()

        # Convert the CRS corners back to pixel coordinates via the
        # inverse affine transform. `~transform * (crs_x, crs_y)` gives
        # (col, row) float pixel coordinates (col right, row down).
        inv = ~transform
        col_f0, row_f0 = inv * (tile_left, tile_top)
        col_f1, row_f1 = inv * (tile_right, tile_bottom)

        # Integer pixel window (row grows down, matching rasterio).
        # ``round()`` already returns ``int``, so no extra ``int()`` cast.
        col_off = round(min(col_f0, col_f1))
        row_off = round(min(row_f0, row_f1))
        col_end = round(max(col_f0, col_f1))
        row_end = round(max(row_f0, row_f1))
        win_w = max(1, col_end - col_off)
        win_h = max(1, row_end - row_off)

        # Fully outside the raster → transparent tile.
        outside = (
            col_off >= raster_w
            or row_off >= raster_h
            or col_off + win_w <= 0
            or row_off + win_h <= 0
        )
        if outside:
            return _transparent_png(tile_size)

        # Clamp the window to the raster. After clamping we track how much
        # padding is needed so the source pixels line up with the correct
        # corner of the output tile.
        src_col = max(0, col_off)
        src_row = max(0, row_off)
        src_col_end = min(raster_w, col_off + win_w)
        src_row_end = min(raster_h, row_off + win_h)
        read_w = max(1, src_col_end - src_col)
        read_h = max(1, src_row_end - src_row)

        window = Window(src_col, src_row, read_w, read_h)
        _sys.stderr.write(
            f"  col_off={col_off} row_off={row_off} col_end={col_end} row_end={row_end}\n"
            f"  clamped src_col={src_col} src_row={src_row} "
            f"read_w={read_w} read_h={read_h}\n"
        )
        _sys.stderr.flush()
        data = src.read(window=window)  # shape (bands, read_h, read_w)

        # Where this read window sits inside the *ideal* tile square.
        # ``win_w`` / ``win_h`` are the size of a full tile in source
        # pixels (before clamping to the raster). ``src_col - col_off`` is
        # how many pixels were clipped on the left, and so on. The window
        # may be clipped differently on X and Y for a non-square raster —
        # we must paste it at the right offset within a transparent canvas
        # WITHOUT stretching it to 256x256, otherwise the tile distorts
        # and neighbours do not line up.
        paste_x_frac = (src_col - col_off) / win_w if win_w > 0 else 0.0
        paste_y_frac = (src_row - row_off) / win_h if win_h > 0 else 0.0
        content_w_frac = (src_col_end - src_col) / win_w if win_w > 0 else 1.0
        content_h_frac = (src_row_end - src_row) / win_h if win_h > 0 else 1.0

    # --- Normalize each band to 0..255 and build an RGBA image -------------
    # We keep the original (min-max) stretch to match the preview look.
    def _stretch(band):
        band = band.astype(np.float32)
        lo = float(np.nanmin(band))
        hi = float(np.nanmax(band))
        if hi <= lo:
            return np.zeros_like(band, dtype=np.uint8)
        return ((band - lo) / (hi - lo) * 255.0).clip(0, 255).astype(np.uint8)

    if bands >= 3:
        rgb = np.stack([_stretch(data[i]) for i in range(3)], axis=-1)
        img = Image.fromarray(rgb, mode="RGB")
    else:
        gray = _stretch(data[0])
        img = Image.fromarray(gray, mode="L").convert("RGB")

    # Resample the read window to exactly tile_size x tile_size.
    # Place the read window into the correct sub-rectangle of a
    # transparent tile_size x tile_size canvas, so that:
    #   * a tile cut from the middle of the raster fills the whole
    #     tile_size x tile_size square (paste_frac = 0, content_frac = 1);
    #   * a tile that overlaps the raster only partly is pasted into the
    #     matching sub-rectangle, with the rest left transparent.
    #
    # Crucially we resize ONLY ONCE — from the read window (read_w x
    # read_h) directly to the target sub-rectangle (content_w x
    # content_h). The previous version first stretched the window to
    # 256x256 and then resized AGAIN, which distorted aspect ratio and
    # produced visible seams between adjacent tiles.
    canvas = Image.new("RGBA", (tile_size, tile_size), (0, 0, 0, 0))
    paste_x = round(paste_x_frac * tile_size)
    paste_y = round(paste_y_frac * tile_size)
    content_w = round(content_w_frac * tile_size)
    content_h = round(content_h_frac * tile_size)
    # Final guard: if the tile touches the raster only by a sub-pixel sliver,
    # content_w/content_h can come out as 0. Paste a single transparent pixel
    # and skip — the tile is effectively empty.
    if content_w > 0 and content_h > 0:
        # There are two distinct regimes here, and they MUST be handled
        # differently — otherwise the user sees "blurry squares" at every
        # zoom level.
        #
        #   (A) read_w >= content_w  ->  the tile holds MORE raster pixels
        #       than it has screen pixels to fill. This is the case at
        #       resolutions >= the raster's native pixel size (e.g. 10 m
        #       for Sentinel-2). We just CROP — no resizing at all — so
        #       one raster pixel maps to at most one screen pixel and no
        #       blur/squares are introduced.
        #
        #   (B) read_w < content_w  ->  the tile holds FEWER raster
        #       pixels than screen pixels. This happens only when zooming
        #       past the raster's native resolution. We resize with
        #       NEAREST so each raster pixel becomes an NxN block of one
        #       solid colour — exactly what QGIS/ArcGIS show.
        #
        # NEAREST is used (not BILINEAR) because bilinear would smear the
        # edge pixels, and different tiles would then compute slightly
        # different edge colours (no shared context).
        if read_w >= content_w and read_h >= content_h:
            # Regime A: downsample by plain cropping — no resize.
            # Take a content_w x content_h sub-window from the centre of
            # the read window so the crop is symmetric and does not
            # introduce a half-pixel shift.
            off_x = max(0, (read_w - content_w) // 2)
            off_y = max(0, (read_h - content_h) // 2)
            cropped = img.crop(
                (off_x, off_y, off_x + content_w, off_y + content_h)
            )
        else:
            # Regime B: upscale with nearest-neighbour — pixelated look.
            cropped = img.resize((content_w, content_h), Image.NEAREST)
        canvas.paste(cropped, (paste_x, paste_y))

    buf = stdlib_io.BytesIO()
    canvas.save(buf, format="PNG", optimize=True)
    return buf.getvalue()


def render_viewport_png(
    raster_path: Path,
    min_x: float,
    min_y: float,
    max_x: float,
    max_y: float,
    out_w: int,
    out_h: int,
) -> bytes:
    """Render an arbitrary viewport of the source raster as an RGBA PNG.

    Unlike `render_tile_png`, this is NOT tied to a fixed 256x256 tile grid.
    The caller supplies a bounding box in the raster's own CRS (typically the
    current OpenLayers view extent) and the desired output size in pixels
    (typically the size of the map viewport on screen). We read exactly the
    raster pixels covered by that bbox and return a single PNG that the
    browser can draw directly.

    Resampling rules (same philosophy as render_tile_png):

      * If the raster window has MORE pixels than the output image
        (i.e. we are zoomed out past the raster's native resolution),
        just CROP a symmetric sub-window — no resampling, no blur.
      * If the raster window has FEWER pixels than the output image
        (i.e. we are zoomed in past the raster's native resolution),
        use Image.NEAREST so each raster pixel becomes a solid NxN block.

    No BILINEAR — the user explicitly wants either 1:1 or pixelated.
    """
    import rasterio
    from rasterio.windows import Window
    from PIL import Image

    out_w = max(1, int(out_w))
    out_h = max(1, int(out_h))

    with rasterio.open(raster_path) as src:
        raster_w = src.width
        raster_h = src.height
        bands = src.count
        transform = src.transform

        # Convert the CRS bbox to pixel coordinates via the inverse affine.
        inv = ~transform
        # bbox in CRS is (min_x, min_y, max_x, max_y) with y going up in CRS.
        # Rasterio row coordinates increase downward, so map both corners
        # and take min/max to get the pixel window.
        col_f0, row_f0 = inv * (min_x, max_y)  # top-left corner in CRS
        col_f1, row_f1 = inv * (max_x, min_y)  # bottom-right corner in CRS

        col_off = int(round(min(col_f0, col_f1)))
        row_off = int(round(min(row_f0, row_f1)))
        col_end = int(round(max(col_f0, col_f1)))
        row_end = int(round(max(row_f0, row_f1)))

        win_w = max(1, col_end - col_off)
        win_h = max(1, row_end - row_off)

        # Clamp to raster bounds. If the requested bbox is entirely outside
        # the raster, return a fully transparent PNG of the requested size.
        if col_off >= raster_w or row_off >= raster_h or col_end <= 0 or row_end <= 0:
            return _transparent_png_size(out_w, out_h)

        src_col = max(0, col_off)
        src_row = max(0, row_off)
        src_col_end = min(raster_w, col_end)
        src_row_end = min(raster_h, row_end)
        read_w = max(1, src_col_end - src_col)
        read_h = max(1, src_row_end - src_row)

        window = Window(src_col, src_row, read_w, read_h)
        data = src.read(window=window)  # shape (bands, read_h, read_w)

        # Build a PIL image from the data.
        if bands >= 3:
            rgb = data[:3].transpose(1, 2, 0)
            img = Image.fromarray(rgb, mode="RGB")
        elif bands == 2:
            gray = data[0]
            img = Image.fromarray(gray, mode="L").convert("RGB")
        else:
            gray = data[0]
            img = Image.fromarray(gray, mode="L").convert("RGB")

        # Resample into the output size, using the crop-vs-nearest rule.
        if read_w >= out_w and read_h >= out_h:
            # Downsampling: crop symmetric sub-window — no blur.
            off_x = max(0, (read_w - out_w) // 2)
            off_y = max(0, (read_h - out_h) // 2)
            cropped = img.crop((off_x, off_y, off_x + out_w, off_y + out_h))
        else:
            # Upsampling: nearest-neighbour — pixelated GIS look.
            cropped = img.resize((out_w, out_h), Image.NEAREST)

        # Place the cropped content at the correct offset within the full
        # viewport canvas, so partial coverage on the edges is transparent.
        canvas = Image.new("RGBA", (out_w, out_h), (0, 0, 0, 0))

        # Where the raster content sits inside the requested bbox:
        # fraction of the bbox that is actually covered by the raster.
        # x fraction: pixels before src_col vs total window pixels.
        full_w = max(1, col_end - col_off)
        full_h = max(1, row_end - row_off)
        paste_x_frac = (src_col - col_off) / full_w
        paste_y_frac = (src_row - row_off) / full_h
        content_w_frac = read_w / full_w
        content_h_frac = read_h / full_h

        paste_x = round(paste_x_frac * out_w)
        paste_y = round(paste_y_frac * out_h)
        content_w = round(content_w_frac * out_w)
        content_h = round(content_h_frac * out_h)

        if content_w > 0 and content_h > 0:
            # Now fit cropped (which is read_w x read_h, already resampled
            # for the visible extent) into the (content_w x content_h)
            # region inside the canvas.
            if cropped.size != (content_w, content_h):
                if cropped.width >= content_w and cropped.height >= content_h:
                    off_x = max(0, (cropped.width - content_w) // 2)
                    off_y = max(0, (cropped.height - content_h) // 2)
                    cropped = cropped.crop(
                        (off_x, off_y, off_x + content_w, off_y + content_h)
                    )
                else:
                    cropped = cropped.resize(
                        (content_w, content_h), Image.NEAREST
                    )
            canvas.paste(cropped, (paste_x, paste_y))

    buf = stdlib_io.BytesIO()
    canvas.save(buf, format="PNG", optimize=True)
    return buf.getvalue()


def _transparent_png_size(w: int, h: int) -> bytes:
    """A fully transparent PNG of arbitrary size."""
    from PIL import Image

    buf = stdlib_io.BytesIO()
    Image.new("RGBA", (max(1, w), max(1, h)), (0, 0, 0, 0)).save(
        buf, format="PNG"
    )
    return buf.getvalue()


def _transparent_png(tile_size: int = 256) -> bytes:
    """A fully transparent square tile (legacy, used by render_tile_png)."""
    return _transparent_png_size(tile_size, tile_size)


def polygon_to_crs(polygon: Polygon, from_crs: CRS, to_crs: CRS) -> Polygon:
    """Reproject a shapely polygon between two CRSs.

    Used when the UI works in a display CRS (e.g. Web Mercator for OSM
    tiles) but the export must be in the raster CRS.
    """
    from pyproj import Transformer
    from shapely.ops import transform as shapely_transform

    transformer = Transformer.from_crs(from_crs, to_crs, always_xy=True)
    return shapely_transform(transformer.transform, polygon)
