"""I/O helpers: GeoTIFF reading and shapefile export.

The one hard rule in this module: a shapefile's .prj must come from the
CRS of the **source raster**, never from a browser view. Web Mercator is
explicitly rejected as an export target - it would silently degrade
polar glacier geometry to metres that mean nothing on the ground.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np
import rasterio
from pyproj import CRS
from shapely.geometry import Polygon


class IOError(RuntimeError):
    """Raised on raster/shapefile I/O problems.

    Name intentionally shadows the builtin: in this module, "IO error" is
    the only meaningful failure mode, and callers catch this specific type.
    """


@dataclass(frozen=True)
class Raster:
    """A GeoTIFF loaded in memory.

    Attributes
    ----------
    data:
        Pixel array with shape ``(bands, height, width)``.
    transform:
        Affine transform mapping pixel coordinates to CRS coordinates.
    crs:
        The raster's CRS (pyproj object).
    path:
        Absolute path the raster was read from (for diagnostics).
    """

    data: np.ndarray
    transform: rasterio.Affine
    crs: CRS
    path: Path

    @property
    def shape(self) -> tuple[int, int]:
        return self.data.shape[1], self.data.shape[2]


def load_geotiff(path: str | Path) -> Raster:
    """Read a GeoTIFF into a :class:`Raster`.

    Loads all bands. Raises :class:`IOError` if the file has no CRS
    (that would break shapefile export later).
    """
    p = Path(path).expanduser().resolve()
    if not p.exists():
        raise IOError(f"GeoTIFF not found: {p}")
    with rasterio.open(p) as src:
        if src.crs is None:
            raise IOError(
                f"GeoTIFF has no CRS: {p}. "
                "Cannot export a shapefile without a defined CRS."
            )
        data = src.read()
        transform = src.transform
        crs = CRS.from_wkt(src.crs.to_wkt())
    return Raster(data=data, transform=transform, crs=crs, path=p)


def export_shapefile(
    polygons: list[Polygon],
    names: list[str] | None = None,
    crs: CRS | None = None,
    out_dir: str | Path = ".",
    name: str = "glacier",
) -> list[Path]:
    """Write one row per polygon to a shapefile in ``out_dir``.

    Parameters
    ----------
    polygons:
        One Polygon per glacier. Every item becomes a separate row in the
        attribute table (a single MultiPolygon would not - that is exactly
        why this function accepts a list).
    names:
        Optional names, one per polygon. Missing entries fall back to
        ``glacier_<i>``. Stored in the ``name`` field of the .dbf.
    crs:
        CRS of every polygon (same for all). Must NOT be EPSG:4326 - the
        caller is expected to reproject first if the map is in lat/lon.
    out_dir:
        Directory to write into; created if missing.
    name:
        Base filename without extension.

    Returns the list of written sidecar files (``.shp``, ``.shx``,
    ``.dbf``, ``.prj``, ``.cpg``). The caller can zip them.

    The ``.prj`` is generated by GDAL from ``crs``. The caller MUST pass
    the raster's CRS (see :func:`load_geotiff`), not a display CRS.
    """
    if not polygons:
        raise IOError("Refusing to export an empty polygon collection.")
    if crs is None:
        raise IOError("CRS is required to export a shapefile.")
    for i, poly in enumerate(polygons):
        if poly.is_empty:
            raise IOError(f"Polygon at index {i} is empty.")
        if not poly.is_valid:
            raise IOError(f"Polygon at index {i} is invalid.")
    if crs.is_geographic and crs.to_epsg() == 4326:
        raise IOError(
            "Refusing to export in EPSG:4326 as-is; reproject to a metric "
            "CRS (UTM / Polar Stereographic) before export."
        )

    # Import lazily so the rest of the package imports without geopandas.
    import geopandas as gpd

    out = Path(out_dir).expanduser().resolve()
    out.mkdir(parents=True, exist_ok=True)

    resolved_names = []
    for i in range(len(polygons)):
        if names is not None and i < len(names) and names[i]:
            resolved_names.append(str(names[i]))
        else:
            resolved_names.append(f"glacier_{i + 1}")

    # Attribute table columns. Shapefile field names are limited to 10
    # characters - "name" and "fid" are safe; longer names get truncated
    # by GDAL with a warning.
    gdf = gpd.GeoDataFrame(
        {
            "fid": list(range(len(polygons))),
            "name": resolved_names,
            "geometry": polygons,
        },
        crs=crs.to_wkt(),
    )
    shp_path = out / f"{name}.shp"
    gdf.to_file(shp_path, driver="ESRI Shapefile", encoding="utf-8")

    written = sorted(out.glob(f"{name}.*"))
    if not written:
        raise IOError(f"Shapefile writer reported success but no files at {out}")
    # Sanity: .prj must exist and be non-empty, otherwise the shapefile is
    # unanchored and ArcGIS/QGIS will refuse to place it on a map.
    prj = out / f"{name}.prj"
    if not prj.exists() or prj.stat().st_size == 0:
        raise IOError(
            "Shapefile written without a .prj - CRS was not propagated. "
            "This is a bug; refusing to return a partially usable result."
        )
    return written


def polygon_to_crs(polygon: Polygon, from_crs: CRS, to_crs: CRS) -> Polygon:
    """Reproject a shapely polygon between two CRSs.

    Used when the UI works in a display CRS (e.g. Web Mercator for OSM
    tiles) but the export must be in the raster CRS.
    """
    from pyproj import Transformer
    from shapely.ops import transform as shapely_transform

    transformer = Transformer.from_crs(from_crs, to_crs, always_xy=True)
    return shapely_transform(transformer.transform, polygon)
